version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8550:8550"
    networks:
      - my_network
    depends_on:
      - backend

networks:
  my_network:
    driver: bridge
